[build-system]
requires = ["hatchling==1.26.3"]
build-backend = "hatchling.build"

[project]
name = "frautnEM"
version = "1.0.5"
requires-python = ">=3.8"
authors = [
  {name = "Edgardo Palazzo", email = "epalazzo@fra.utn.edu.ar"},
]
description = "A set of library functions to be used in courses of electromagnetism."
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE.txt"]
keywords = ["electromagnetism", "Physics", "Python", "course", "UTN"]
classifiers = [
  "Programming Language :: Python"
]

[project.urls]
Homepage = "https://github.com/frautn/frautnEM"
# Documentation = "https://readthedocs.org"
Repository = "https://github.com/frautn/frautnEM.git"
"Bug Tracker" = "https://github.com/frautn/frautnEM/issues"
# Changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[tools.setuptools]
packages = ["src"]